### ISSUE TITLE
Display of Task names

### ISSUE THREAD

**Issue by Syed-Google** [google/ezgantt#2]
When a task name is long, the display cuts off from the left hand side in the display.

Can we make sure we support higher number of words for display in the task name. Currently it cuts off task name from left side after 30 characters

**Comment by salamanders** [comment]
It squashes the rest of the chart if I put in a "gantt: {
  labelMaxWidth:900
}" config setting.  

I can't set an "overflow: 'auto'" in the style because it is a SVG.
The hover should show the full title.

Please reopen if you have ideas!
