### ISSUE TITLE
Demo doesn't load

### ISSUE THREAD

**Issue by davelab6** [google/ezgantt#3]
I just get "app error"

**Comment by salamanders** [comment]
Are you signed in to a gmail account?  I get redirected to https://ezgantt.appspot.com/#1kYfoEFXW-psZ8AMy0Ne7wRMiM3umNKBs3v9U7nvafXA which seems to be working.

**Comment by davelab6** [comment]
Yes, I am signed in to d.crossland@gmail.com

This is the app error alert:

![screen shot 2017-10-04 at 18 47 25](https://user-images.githubusercontent.com/261579/31203302-812af164-a934-11e7-9fd8-1715e0363675.png)

After dismissing it, I can drill down the console to see more info:

![screen shot 2017-10-04 at 18 47 31](https://user-images.githubusercontent.com/261579/31203303-812f5a92-a934-11e7-8b8a-66a8e2d7ec53.png)

Interestingly when I am signed into my-ldap@google.com then instead of the error, I see a "sign in with Google" button in the center of the page

**Comment by salamanders** [comment]
I have no idea!  Never seen that before.  Some odd extension, or debugging mode, or permission thing?  What if you use a different browser?

**Comment by salamanders** [comment]
Sorry, can't repro.  Not sure why this would happen.
