### ISSUE TITLE
ezGantt link permission denied

### ISSUE THREAD

**Issue by j4ml3t** [google/ezgantt#5]
Hi guys, first of all I have to say that this feature is great, and it is well appreciate from my side. But I have an error, and it is that when sharing the document with other person, this person is not allow to see the ezGantt link, they can edit the spreadsheet but a popup appears when you click on ezGantt link that says that you don't have access to it.

Am I missing something to share the whole thing? that is the spreadsheet itself and the privilege to access the ezGantt.

Thanks in advance

**Comment by salamanders** [comment]
Stale, closing, please re-open if you can repro the issue
