### ISSUE TITLE
Why the sign in btn?

### ISSUE THREAD

**Issue by musicteachj** [google/ezgantt#9]
I'm currently working on a gantt project for work, I was interested in viewing your gantt example, but I'm not interested in letting anyone access my google account. Just giving some feedback. :)

**Comment by salamanders** [comment]
I think it is required for the app's JavaScript to read the sheet. I'm open to options if there are other ways to grant access!

**Comment by salamanders** [comment]
Please reopen if someone has a way to run this with a more restricted Auth scope.
